apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: zammad-elasticsearch
  name: zammad-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zammad-elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: zammad-elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms1g -Xmx1g
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          image: elasticsearch:9.4.2
          name: zammad-elasticsearch
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
      restartPolicy: Always
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-data
