pipeline {
    //1. DooD (호스트 도커 소켓 공유)
    agent any 
    //2. DinD (컨테이너 안에서 새로운 도커 실행, jenkins 에이전트마다 별도의 도커 데몬 띄워야함)
    //agent {
    //docker {
    //    image 'docker:24-cli'
    //    args '-v /run/podman/podman.sock:/var/run/docker.sock --privileged --entrypoint=""'
    //}
}

    environment {
        IMAGE_NAME = "ghcr.io/jaeylim/jaeylim-test-repo"
        IMAGE_TAG = "jenkins-test"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Image') {
            steps {
                sh 'docker buildx build --load -t $IMAGE_NAME:$IMAGE_TAG .'
            }
        }

        stage('Login to GHCR') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'ghcr-credentials', usernameVariable: 'GHCR_USER', passwordVariable: 'GHCR_TOKEN')]) {
                    sh 'echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USER --password-stdin'
                }
            }
        }

        stage('Push Image') {
            steps {
                sh 'docker push $IMAGE_NAME:$IMAGE_TAG'
            }
        }
    }
}
